# Site
repository: thombauer/resume
favicon: images/favicon.ico

# Personal info
name: Thom Bauer
title: Data Scientist & ML/AI Product Manager
email: thom.bauer@hotmail.com
website: www.github.com/thombauer/resume

# Social links
# twitter_username: facespics
github_username:  thombauer
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thom_saw
linkedin_username: thombauer
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/Bauer_Thomas_07_2025.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Thom and I'm a data scientist, product owner and product manager.

  I am most skilled in: <mark>Python</mark> and <mark>Tableau</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and code some of my other interests and hobbies are:
   - Basketball
   - Music
   - Photography

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
