# Site
repository: thombauer/resume
favicon: images/favicon.ico

# Personal info
name: Thom Bauer
title: Data Scientist | Product Owner | ML/AI Product Manager
email: thom.bauer@hotmail.com
website: thombauer.github.io
DataCamp: datacamp.com/portfolio/thombauer-c

# Social links
# twitter_username: facespics
github_username:  thombauer
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: thom_saw
linkedin_username: thombauer
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

gtag: "UA-172319848-1"

# About Section
# about_title: About Me
about_profile_image: images/Bauer_Thomas_07_2025.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I’m Thom, a Data Scientist and Product Owner with a master’s degree in Sociology and Psychology, and advanced certifications in Data Science and Machine Learning. I’m passionate about emerging technologies and continually expanding my skill set. With a strong background in teaching coding and data concepts, I’m always eager to learn and grow.

  With over 10 years of management experience as a Team Lead, Head of IT Operations, and Head of Data Analytics, I focus on customer-centricity and clear communication as key drivers of success. I’ve always prioritized Customer Satisfaction and Experience Management, both in my leadership roles and product development.

  Over my 20+ years as a coder and analyst, I’ve mastered various programming languages and tools. I’m constantly exploring new techniques to improve efficiency and future-proof my approach.

  As a Data Scientist, I specialize in building Machine Learning models that enhance customer experiences and automate text processing for streamlined workflows. At the intersection of Data Science and Social Sciences, I’m working with explainable AI (xAI) to ensure transparent, human-friendly decision-making in automated systems.

  I’m deeply engaged in AI’s latest advancements and enjoy exchanging ideas with other companies to deploy AI solutions that maximize business value.

  In addition to my hands-on experience, I am also passionate about sharing knowledge. I have had the privilege of presenting at congresses and conferences, lecturing in university programs and leading practical training sessions for non-technical professionals.
  
  I possess advanced expertise in <mark>Python</mark> and <mark>Tableau</mark>, with a strong command of <mark>R</mark>. Currently, I am enhancing my proficiency in <mark>PowerBI</mark> and <mark>generative AI</mark> to further broaden my technical capabilities.
  
  As a ML/AI Product Manger I maximize the value of innovative Machine Learning solutions to build the future claims products in the Social Insurance Industry.

  ![PSPOI_icon](https://github.com/thombauer/thombauer.github.io/raw/master/assets/img/pspoI_icon.png "Logo PSPOI")
  ![DataCamp_icon](https://github.com/thombauer/thombauer.github.io/raw/master/assets/img/data_camp.jpeg "Logo DataCamp")
  

# Projects Section
projects_title: Skills / Tools

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Bildungsweg

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and code some of my other interests and hobbies are:
   - Basketball (#nevernotballin), Beachvolleyball, Running
   - Gardening, highly automated ;)
   - Skateboarding
   - Music
   - Photography

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
